import Head from 'next/head';
import Menu from '../components/menu';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import MainMap from './maps/map';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Menu />
        {/* <h1>HOME</h1> */}
        <MainMap />

      </main>
    </>
  );
}
