import Head from 'next/head';
import Menu from '../components/menu';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import MainMap from './maps/map';
import MapBox from '../components/mapBox';
import DataTabToggle from '../components/dataTabToggle';
import DataTab from '../components/dataTab'
const inter = Inter({ subsets: ['latin'] });
import { useAppContext } from '../context/journeys';
import JourneyNav from '../components/journeyNav';
import { createContext, useState } from 'react';


export const SectionContext = createContext({
  currentSection: null,
  setSection: (() => { }),
})


export default function Home() {
  const journeys = useAppContext()
  const [currentSection, setSection] = useState(null)
  const sectionValue = { currentSection, setSection }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SectionContext.Provider value={sectionValue}>

          <Menu journeys={journeys} />
          {/* <h1>HOME</h1> */}
          <MainMap />
          {/* <MapBox /> */}
          <JourneyNav journeys={journeys} />
        </SectionContext.Provider>

      </main>
    </>
  );
}
